---
title: "Ocean Halos: Methods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This document outlines the methods used to model the ocean halos concept. 

## Intent/Research Questions

Given growing interest in meeting marine conservation targets with the implementation of large-scale marine protected areas (LSMPAs), we find that relatively little attention has been paid to how to finance the costs of enforcing such large ocean areas. 

We present one possible mechanism for financing LSMPAs, termed the "Ocean Halos" model, in which a no-take MPA is surrounded by a controlled fishing areas, in which access is only allowed through a leasing scheme. This model operates on the premise that MPAs have the potential to provide benefits in the form of fish spillover from within the reserve to fisheries outside. Depending on the placement of the MPA (and the management regime outside of the MPA), those benefiting from the spillover may not be the same as those responsible for managing the MPA. We therefore propose that countries interested in implementing MPAs, particularly LSMPAs, should consider including a mechanism such as the "Ocean Halos" model in order to capitalize on the financial benefits created from effectively conserving marine resources. These financial benefits could offer a long-term financing mechanism to support the significant enforcement costs associated with monitoring and enforcement of LSMPAs. 

We ask the following questions: 
- How large would the lease area need to be relative to the the reserve area (for a given stock and its dynamics) to offset the enforcement costs of both areas? 
- How much effort will be allowed in the fishing zone (or, how much to charge)?

## Model

To illustrate the Ocean Halos concept, we use a simple model with two patches. 

Patch A contains no fishing and is thereofe a *de facto* marine reserve. Patch B opperates under open access. Patches are connected with each other through dispersal, such that spillover from the *de facto* reserve in patch A provide benefits to patch B. Patch A then considers opening a portion of it's waters to fishing, so as to capture some of the benefits from the conservation occurring in its waters.

### Fishery dynamics

Building from our classic bioeconomic model, harvest from fishing in patch $i$ ($H_i$) is given by:

$$
H_i = qE_iX_i
$$
where $q$ is catchability, $E_i$ is fishing effort in patch B, and $X_i$ is stock biomass in patch B. 

At constant price $p$, this harvest produces revenue $pqE_iX_i$, which is achieved at cost $cE_i^\beta$ where $\beta = 1.3$ assumes that increasing units of effort are increasingly costly to apply. Therefore, profits from fishing in patch $i$ ($\pi_i$) are given by:

$$
\pi_i = pqE_iX_i - cE_i^\beta
$$
where $c$ is a cost coefficient. 

When patch A opens a portion of its waters to fishing, a portion of it's biomass becomes "visible" to the fleet. The portion of fishable biomass is determined by within-patch fish movement ($\theta$, i.e. how mobile the fish are) and the size of the fishing zone ($1 - R$, where $R$ indicates the proportion of the patch as a reserve). Therefore, we can define a scalar $\Omega = \theta R + (1 - R)$.

Therefore we can rewrite the profit equation using the scalar as

$$
\pi_i = pqE_iX_i\Omega_i - cE_i^\beta
$$

We assume that in patch B, $\Omega_B = 1$. 

By taking the derivative of profits with respect to effort ($\frac{d}{dE_i}(\pi_i)$), we can then calculate marginal profits as

$$
\frac{d}{dE_i}(\pi_i) = pqX_i\Omega_i - \beta cE_i^{(\beta - 1)}
$$

which implies that a marginal unit of effort will produce $\frac{d}{dE_i}(\pi_i)$, which should also be maximum amount that a vessel would be willing to pay to fish inside an area for a given unit of effort. 

In patch B, marginal profits must be equal to zero following open access dynamics, and we can then calculate effort in patch B as

$$
E_B = \left(\frac{pqX_B}{\beta c}\right)^{\left(\frac{1}{\beta - 1}\right)}
$$

In patch A, allowable effort in the lease area would be set by management. This could be done in a number of ways:
1) For a given reserve size ($R$), what combination of access fee and effort maximizes lease revenues. 
2) Set a target total escapement. 
3) Solve the DPE (which, for all I know might yield the same results). 

### Enforcement costs












### Stock dynamics

We assume that the biological characteristics of the stock follows a Pella-Tomlinson growth function. At the end of each time step, escapement in each patch is defined as 

$$
S_i = X_i - H_i
$$

Total escapement is therfore given by 
$$
S_{t} = \sum^{i} S_{i,t}
$$
The total escaped population then grows according to the following growth function... 

> PELLA TOMLINSON HERE

## Parameterization



