---
title: "Fishing effort around SIDS"
output: html_notebook
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, message = FALSE)
```
```{r}
# Necessary libraries
library(tidyverse)
library(bigrquery)
library(sf)
library(lwgeom)

# Bigquery project
ucsb_project <-  "ucsb-gfw"

# Read in EEZ data
eez_boundaries <- st_read(here::here("data", "World_EEZ_v10_20180221/"), layer="eez_boundaries_v10", stringsAsFactors=FALSE, as_tibble=TRUE) %>%
    filter(Line_type == "200 NM") %>%
  dplyr::select(mrgid_eez = MRGID_EEZ1, territory = Territory1, sovereign = Sovereign1) 

# Make land
world_land <-
  st_as_sf(rworldmap::countriesLow) ## data(countriesLow) is from the rworldmap package

# Results directory for plots
results_dir <- here::here("results", "effort-by-distance-SID")
if (dir.exists(results_dir) == F) {
  dir.create(results_dir, recursive = T)
}

```

```{r}
# Aggregate and download our full SIDs dataset 
sql <- "
SELECT
 *
FROM
  `ucsb-gfw.ocean_halos.final_eez_dataset_SID`
"

final_eez_dataset <- bq_project_query(ucsb_project, sql) %>% 
  bq_table_download(max_results = Inf)

# write_csv(final_eez_dataset, path = here::here("data", "final_eez_dataset_SID_2016_2018.csv"))

```

```{r}
# Make analysis plots for 2018
dataset_filter_2018_0.1deg <- final_eez_dataset %>%
  filter(year == 2018) %>%
  mutate(lat_bin = floor(lat_bin / 0.1) * 0.1 + 0.05,
         lon_bin = floor(lon_bin / 0.1) * 0.1 + 0.05,
         distance_to_eez_boundary_km = distance_to_eez_boundary_meters / 1000) %>%
  group_by(mrgid_eez, lat_bin, lon_bin) %>%
  summarize(fishing_hours = sum(fishing_hours),
            distance_to_eez_boundary_km = mean(distance_to_eez_boundary_km))

# 0.1 Degree Plot
fishing_line_plot_0.1deg <- dataset_filter_2018_0.1deg %>%
  ggplot()+
  geom_sf(data=world_land, color = NA, fill="grey30") +
  geom_tile(aes(x = lon_bin, y=lat_bin, fill = fishing_hours)) +
  geom_sf(data=eez_boundaries, color="grey80", size=0.1, aes(group = mrgid_eez)) +
  scale_fill_viridis_c(trans="log", name="Fishing hours", breaks = c(1, 10, 100, 1000)) +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  xlab("") +
  ylab("") +
  theme(plot.title = element_text(color="black",hjust=0,vjust=1, size=20),
        panel.background = element_rect(fill ="black"),
        plot.background = element_rect(fill = "black"),
        legend.background=element_rect(fill="black"),
        legend.text = element_text(color = "white", size = 16),
        legend.title = element_text(color = "white", size = 16),
        legend.title.align = 1,
        legend.direction="horizontal",
        legend.position = "bottom",
        legend.justification = "center",
        axis.text = element_text(color = "white", size = rel(1)),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
 guides(fill=guide_legend(
                 keywidth=0.25,
                 keyheight=0.25,
                 default.unit="inch")) +
  ylim(c(-55,90))

ggsave(paste0(results_dir, "/high_seas_effort_map_0.1deg.png"), dpi = 200, width = 7, height = 4)


# 0.25 Degree Plot
dataset_filter_2018_0.25deg <- final_eez_dataset %>%
  filter(year == 2018) %>%
  mutate(lat_bin = floor(lat_bin / 0.25) * 0.25 + 0.125,
         lon_bin = floor(lon_bin / 0.25) * 0.25 + 0.125,
         distance_to_eez_boundary_km = distance_to_eez_boundary_meters / 1000) %>%
  group_by(mrgid_eez, lat_bin, lon_bin) %>%
  summarize(fishing_hours = sum(fishing_hours),
            distance_to_eez_boundary_km = mean(distance_to_eez_boundary_km))

fishing_line_plot_0.25deg <- dataset_filter_2018_0.25deg %>%
  ggplot()+
  geom_sf(data=world_land, color = NA, fill="grey30") +
  geom_tile(aes(x = lon_bin, y=lat_bin, fill = fishing_hours)) +
  geom_sf(data=eez_boundaries, color="grey80", size=0.1, aes(group = mrgid_eez)) +
  scale_fill_viridis_c(trans="log", name="Fishing hours", breaks = c(1, 10, 100, 1000)) +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0))+
  xlab("") +
  ylab("") +
  theme(plot.title = element_text(color="black",hjust=0,vjust=1, size=20),
        panel.background = element_rect(fill ="black"),
        plot.background = element_rect(fill = "black"),
        legend.background=element_rect(fill="black"),
        legend.text = element_text(color = "white", size = 16),
        legend.title = element_text(color = "white", size = 16),
        legend.title.align = 1,
        legend.direction="horizontal",
        legend.position = "bottom",
        legend.justification = "center",
        axis.text = element_text(color = "white", size = rel(1)),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
 guides(fill=guide_legend(
                 keywidth=0.25,
                 keyheight=0.25,
                 default.unit="inch")) +
  ylim(c(-55,90))

ggsave(paste0(results_dir, "/high_seas_effort_map_0.25deg.png"), dpi = 200, width = 7, height = 4)

```

```{r}
# Load in conversion sheet with country names
country_list <- read_csv(here::here('data', "SID_country_list.csv"))

dataset_filter_10km <- final_eez_dataset %>%
  filter(year == 2018) %>%
  mutate(distance_to_eez_boundary_km = ifelse(inside_eez == FALSE, distance_to_eez_boundary_meters / 1000, -1*(distance_to_eez_boundary_meters / 1000))) %>%
  group_by(mrgid_eez) %>%
  mutate(distance_to_eez_rounded_km = ifelse(distance_to_eez_boundary_km >=0, 
                                             ceiling(distance_to_eez_boundary_km/10)*10,
                                             floor(distance_to_eez_boundary_km/10)*10)) %>%
  ungroup() %>%
  group_by(mrgid_eez, distance_to_eez_rounded_km) %>%
  summarize(fishing_hours = sum(fishing_hours)) %>%
  mutate(bin_size = "10 km")

dataset_filter_20km <- final_eez_dataset %>%
  filter(year == 2018) %>%
  mutate(distance_to_eez_boundary_km = ifelse(inside_eez == FALSE, distance_to_eez_boundary_meters / 1000, -1*(distance_to_eez_boundary_meters / 1000))) %>%
  group_by(mrgid_eez) %>%
  mutate(distance_to_eez_rounded_km = ifelse(distance_to_eez_boundary_km >=0, 
                                             ceiling(distance_to_eez_boundary_km/20)*20,
                                             floor(distance_to_eez_boundary_km/20)*20)) %>%
  ungroup() %>%
  group_by(mrgid_eez, distance_to_eez_rounded_km) %>%
  summarize(fishing_hours = sum(fishing_hours)) %>%
  mutate(bin_size = "20 km")

dataset_filter_40km <- final_eez_dataset %>%
  filter(year == 2018) %>%
  mutate(distance_to_eez_boundary_km = ifelse(inside_eez == FALSE, distance_to_eez_boundary_meters / 1000, -1*(distance_to_eez_boundary_meters / 1000))) %>%
  group_by(mrgid_eez) %>%
  mutate(distance_to_eez_rounded_km = ifelse(distance_to_eez_boundary_km >=0, 
                                             ceiling(distance_to_eez_boundary_km/40)*40,
                                             floor(distance_to_eez_boundary_km/40)*40)) %>%
  ungroup() %>%
  group_by(mrgid_eez, distance_to_eez_rounded_km) %>%
  summarize(fishing_hours = sum(fishing_hours)) %>%
  mutate(bin_size = "40 km")

dataset_filter_100km <- final_eez_dataset %>%
  filter(year == 2018) %>%
  mutate(distance_to_eez_boundary_km = ifelse(inside_eez == FALSE, distance_to_eez_boundary_meters / 1000, -1*(distance_to_eez_boundary_meters / 1000))) %>%
  group_by(mrgid_eez) %>%
  mutate(distance_to_eez_rounded_km = ifelse(distance_to_eez_boundary_km >=0, 
                                             ceiling(distance_to_eez_boundary_km/100)*100,
                                             floor(distance_to_eez_boundary_km/100)*100)) %>%  
  ungroup() %>%
  group_by(mrgid_eez, distance_to_eez_rounded_km) %>%
  summarize(fishing_hours = sum(fishing_hours)) %>%
  mutate(bin_size = "100 km")

dataset_filter_2018 <- dataset_filter_10km %>%
  bind_rows(dataset_filter_20km) %>%
  bind_rows(dataset_filter_40km) %>%
  bind_rows(dataset_filter_100km)
  
country_data_2018 <- dataset_filter_2018 %>%
  left_join(country_list, by = "mrgid_eez")

country_names <- unique(country_data_2018$country_name)

for(i in 1:length(country_names)){
  
  name_nospace <- gsub("\\s", "", country_names[i]) 
  file_name <- paste0("comp_bin_sizes_", name_nospace)
  
  plot <- country_data_2018 %>%
  dplyr::filter(country_name == country_names[i]) %>%
  ggplot() +
  aes(x = distance_to_eez_rounded_km, y = fishing_hours, group = country_name, fill = distance_to_eez_rounded_km) +
  geom_point(size = 4, shape = 21) +
  geom_vline(xintercept = 0)+
  scale_fill_gradient2(low =scales::muted("blue"), mid = "white", high = scales::muted("red"), midpoint = 0)+
  facet_wrap(~bin_size, ncol = 2, scales = "free") +
  theme_bw()+
  labs(title = paste0("Fishing effort by distance to SID EEZ boundaries (2018) - ", country_names[i]), x = "Distance to EEZ boundary (km)", y = "Fishing hours")+
  theme(legend.position = "none")
  
  ggsave(paste0(results_dir, "/comp_bin_sizes_country/", file_name, ".png"), dpi = 200, width = 12, height = 10)
}

```

